---
name: Angular App CI/CD
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: |
          npm install -g @angular/cli
          npm install --legacy-peer-deps
      - name: Build the App
        run: ng build --configuration production --aot

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
